### ISSUE TITLE
Dashboard times out trying to load peers.

### ISSUE THREAD

**Issue by ComradeCluck** [donaldzou/WGDashboard#128]
I'm setting up the dashboard with an existing configuration file that has ~60 peers.

Everything works as expected for a while then the dashboard seems to get stuck loading the configuration.

There is a traceback in the log file:

`[2022-01-11 18:54:57,752] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 779, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 327, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 269, in get_all_peers_data
    search = db.search(peers.id == i['PublicKey'])
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 233, in search
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 233, in <listcomp>
    docs = [doc for doc in self if cond(doc)]
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 603, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/usr/local/lib/python3.7/dist-packages/tinydb/table.py", line 653, in _read_table
    tables = self._storage.read()
  File "/usr/local/lib/python3.7/dist-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 21333 (char 21332)`

Any help would be appreciated and thank you for your time!

**Comment by donaldzou** [comment]
Hi, this seems like there a peers in your configuration does not have a public key, could you check that please? And I will also look on my side to prevent this in the future ;)

**Comment by ComradeCluck** [comment]
I'll look through my configuration file. Thank you!

**Comment by ComradeCluck** [comment]
I can confirm that every peer in the configuration file has a public key. Deleting the db json file gets the dashboard back to a working state and is still currently working after adding the peers. Not sure what caused the issue. Thanks for your help!

**Comment by donaldzou** [comment]
Hi! Thank you for returning back to me, I think this caused by how the dashboard designed in the first place. Since it is using a file based database, it does not have implement semaphore on critical area cuz flask is multi-threaded. Therefore it might crash the database when accessing it with multiple thread the same time. I'm planning to release v3.0, which is transform it with using thread-safe database, please stay tuned!
