### ISSUE TITLE
SQLite needed for installation?

### ISSUE THREAD

**Issue by mmb14** [donaldzou/WGDashboard#142]
I followed all instructions for installation from scratch with the following:

Ubuntu 20.04.3
PIP 21.3.1
Python 3.8.10
WG/WG-tools

When the installation is complete, I try to access the webpage, there is an error in the browser:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

When running ./wgd.sh debug I get this:

user@vpn:~/wgdashboard/src$ ./wgd.sh debug
------------------------------------------------------------
| Starting WGDashboard in the foreground.                  |
 * Serving Flask app 'WGDashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.99.0.225:10086/ (Press CTRL+C to quit)
[2022-01-26 16:04:28,665] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 637, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 61, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.99.1.206 - - [26/Jan/2022 16:04:28] "GET / HTTP/1.1" 500 -
[2022-01-26 16:04:28,737] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 637, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 61, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.99.1.206 - - [26/Jan/2022 16:04:28] "GET /favicon.ico HTTP/1.1" 500 -

It seems to be trying to access a database file that doesn't exist.

I notice that there is mention in the changelog that there has been a move from TinyDB to SQLite but there is no mention of SQLite in the installation instructions.  Are we supposed to install this separately or should the WGdashboard installer call for the the installation?  And if we are to install it separately, how do we link WGdashboard to the DB?

**Comment by donaldzou** [comment]
Hi, there are no need to install SQLite, Python already included it. I'm suspecting is because python does not have the permission to read files. Could you please try to run it with `sudo ./wgd.sh debug` and see if this would help ;)

**Comment by mmb14** [comment]
Thanks - that was it!

**Comment by donaldzou** [comment]
Hi, I'm glad we solved this!! If you do not want to run in `sudo` mode, you can do the following `sudo chown -R user:user wgdashboard` from the folder where it contain the dashboard's folder ;)

**Comment by mmb14** [comment]
Perfect Thanks!
