### ISSUE TITLE
Error fresh install

### ISSUE THREAD

**Issue by PrzemekSkw** [donaldzou/WGDashboard#149]
Hello, I delete whole wgdashboard dir and install fresh wg-dashboard.
When I start I have that error:
```
sudo ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/przemko/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/przemko/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/przemko/wgdashboard/src/dashboard.py", line 6, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
| Log files is under log/                                  |
```
OS: CentOS 7
Python: 3.7.11
Regards.

**Comment by donaldzou** [comment]
Hi! I'm sorry that you encountered an issue, please check this out https://unix.stackexchange.com/a/611608 , it might solve your problem ;)

**Comment by PrzemekSkw** [comment]
I install and configure sqlite3 and now works.
Regards.

**Comment by donaldzou** [comment]
I'm glad it worked out ;)
