### ISSUE TITLE
Can’t connect from local machine to AWS server Wireguard

### ISSUE THREAD

**Issue by lavaw** [donaldzou/WGDashboard#163]
I can’t connect from my local machine to aws server’s WireGuard to open wgdashboard.  
how can I resolve this problem? I didn’t know what kind of IP address I need to enter

**Comment by donaldzou** [comment]
Hi, usually you just need to enter your AWS server's public IP and the port: `http://<public_ip>:10086`. Also you need to open in-coming and out-going traffic on both AWS control panel, and the server's firewall.

**Comment by lavaw** [comment]
Thank u for answer!
But I can connect to my vpn. 
I can’t connect to dashboard only… can u tell me step-by-step instruction, how to do it pls. I’m newbie in ubuntu:(

**Comment by lavaw** [comment]
Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/ubuntu/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/home/ubuntu/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/           

Is it OKAY?

**Comment by donaldzou** [comment]
Hi, did you followed my install instructions on https://github.com/donaldzou/WGDashboard#-install ?

**Comment by lavaw** [comment]
yes, of course

**Comment by donaldzou** [comment]
I see, it seems like it didn't install all dependencies correctly.

Could you go into `wgdashboard/src` and type `python3 -m pip install -r requirements.txt`? Please let me know how it goes ;)

**Comment by lavaw** [comment]
I do that) Didn't have errors now, but I can't connect to dashboard. Am I should to change wh-dashboard.ini?

**Comment by donaldzou** [comment]
I don’t think so. Can you check your system’s firewall to allow port 10086? And also check AWS ‘s security setting to allow that port :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lavaw** [comment]
I have opened all UDP ports in my AWS
May be I can't change port in wg-dashboard?

**Comment by donaldzou** [comment]
You need to open TCP port too for the dashboard:) since is using HTTP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lavaw** [comment]
I have change app_ip to my external AWS ip , isn't true?

**Comment by lavaw** [comment]
After open ports I need to restart system?

**Comment by lavaw** [comment]
I have open all TCP ports in dashboard

**Comment by donaldzou** [comment]
> I have change app_ip to my external AWS ip , isn't true?

I think you should keep it as `0.0.0.0`, and you should be good after you opened all your TCP port

**Comment by lavaw** [comment]
If it's 0.0.0.0, I could connect to my VPN server through external AWS IP address ?

**Comment by lavaw** [comment]
Anyway I can't connect to dashboard( 
 "Starting WGDashboard with Gunicorn in the background.    |
| Log files is under log/   "

**Comment by donaldzou** [comment]
Or could you try run the dashboard with `./wgd.sh debug`? instead of `start`

**Comment by lavaw** [comment]
Starting WGDashboard in the foreground.                  |
 * Serving Flask app 'WGDashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.*.*.*:10086/ (Press CTRL+C to quit)

**Comment by lavaw** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.0.0.2 - - [25/Mar/2022 18:08:07] "GET / HTTP/1.1" 500 -
[2022-03-25 18:08:08,048] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.0.0.2 - - [25/Mar/2022 18:08:08] "GET /favicon.ico HTTP/1.1" 500 -
[2022-03-25 18:08:12,365] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.0.0.2 - - [25/Mar/2022 18:08:12] "GET / HTTP/1.1" 500 -
[2022-03-25 18:08:13,371] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
10.0.0.2 - - [25/Mar/2022 18:08:13] "GET / HTTP/1.1" 500 -
[2022-03-25 18:08:21,892] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
77.238.248.155 - - [25/Mar/2022 18:08:21] "GET / HTTP/1.1" 500 -
[2022-03-25 18:08:22,007] ERROR in app: Exception on /apple-touch-icon-precomposed.png [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
77.238.248.155 - - [25/Mar/2022 18:08:22] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 500 -
[2022-03-25 18:08:22,018] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
77.238.248.155 - - [25/Mar/2022 18:08:22] "GET /favicon.ico HTTP/1.1" 500 -
[2022-03-25 18:08:22,093] ERROR in app: Exception on /apple-touch-icon.png [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "dashboard.py", line 638, in auth_req
    g.db = connect_db()
  File "dashboard.py", line 65, in connect_db
    return sqlite3.connect(os.path.join(configuration_path, 'db', 'wgdashboard.db'))
sqlite3.OperationalError: unable to open database file
77.238.248.155 - - [25/Mar/2022 18:08:22] "GET /apple-touch-icon.png HTTP/1.1" 500 -

**Comment by lavaw** [comment]
Help me pls) We so close to resolve this problem

**Comment by donaldzou** [comment]
I see what is going on now, you need to run the dashboard with sudo, `sudo ./wgd.sh start` or `sudo ./wgd.sh debug` ;)

**Comment by lavaw** [comment]
Done. But doesn't loading page..

**Comment by donaldzou** [comment]
What will output when you run `sudo ./wgd.sh debug`?

**Comment by lavaw** [comment]
CONNECTED!!! BUT ONLY WITH VPN CONNECTION(

**Comment by donaldzou** [comment]
Nicee, did you set it back to `0.0.0.0` in the `wgdashboard.ini`?

**Comment by lavaw** [comment]
Yes, but without vpn I haven’t access (

**Comment by donaldzou** [comment]
Maybe there are some whitelist of IPs on AWS that preventing you to do it?

**Comment by donaldzou** [comment]
In your Security group rules, in the AWS dashboard you need to allow: `80` & `10086` on TCP and the source needs to be `0.0.0.0/0`

**Comment by lavaw** [comment]
Anyway can't connect without vpn to dashboard

**Comment by gangstead** [comment]
I had a few of these problems running on an AWS EC2 instance and here's what I had to do:

1. In the security group used by the EC2 instance add an Ingress for TCP port 10086.  
    - In my case I don't want the dashboard exposed to the internet, only available when you have wireguard connected.  So I limit the source to CIDR block `10.0.0.0/8` (all internal traffic).  Then I connect to the dashboard at my Wireguard Server's internal address at `http://10.0.0.X:10086`
    - I'm able to do this because I've already got wireguard up and running and my first peer profile created and working before installing this dashboard.  If you're trying to use the wg dashboard to create all the peers you'll need CIDR block to give the world access `0.0.0.0/0` and you can always go back and change it later.
3. I followed the install instructions (I think!) and ended up with `log/`, `db/` and `__pycache__/` directories owned by root and not my default "ubuntu" user. This caused the `db/` folder to not be readable and gave me the `unable to open database file` sqlite errors.  I fixed it with `sudo chown ubuntu:ubuntu db/ log/ __pycache__/`

**Comment by DaanSelen** [comment]
Is this fixed @lavaw
