### ISSUE TITLE
no running new version

### ISSUE THREAD

**Issue by Geracl** [donaldzou/WGDashboard#168]
**Describe The Problem**
Не работает

**Expected Error / Traceback**
```
root@fin:~# git clone -b hmm-what-about-socket https://github.com/donaldzou/WGDa                               shboard.git wgdashboard
Cloning into 'wgdashboard'...
remote: Enumerating objects: 1839, done.
remote: Counting objects: 100% (1024/1024), done.
remote: Compressing objects: 100% (474/474), done.
remote: Total 1839 (delta 783), reused 689 (delta 535), pack-reused 815
Receiving objects: 100% (1839/1839), 11.21 MiB | 9.04 MiB/s, done.
Resolving deltas: 100% (1182/1182), done.
root@fin:~# cd wgdashboard/src
root@fin:~/wgdashboard/src# sudo chmod u+x wgd.sh
root@fin:~/wgdashboard/src# sudo ./wgd.sh install
------------------------------------------------------------
| Starting to install WGDashboard                          |
| Upgrading pip                                            |
| Installing latest Python dependencies                    |
| WGDashboard installed successfully!                      |
| Enter ./wgd.sh start to start the dashboard              |
------------------------------------------------------------
root@fin:~/wgdashboard/src# ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 111,                                in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/root/wgdashboard/src/dashboard.py", line 28, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
| Log files is under log/                                  |
------------------------------------------------------------

```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: [e.g. Ubuntu 18.02]
 - Python Version: [e.g v3.8]

**Sample of your `.conf` file**
```
Please provide a sample of your configuration file that you are having problem with. You can replace your public key and private key to ABCD...

**Comment by donaldzou** [comment]
Hi could you please try to pull now? I removed some code that should get removed.

**Comment by donaldzou** [comment]
Please check the newest push ;)
