### ISSUE TITLE
Failed to read config file: .../gunicorn.conf.py

### ISSUE THREAD

**Issue by iilliya** [donaldzou/WGDashboard#189]
Hi 
i install the dashboard and python 3 and pip via 

`sudo apt install python3-pip`
Installation  completed without any error but start it output this error :

`------------------------------------------------------------

| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /home/iliya/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/iliya/wgdashboard/src/gunicorn.conf.py", line 4, in <module>
    app_host, app_port = dashboard.get_host_bind()
  File "/home/iliya/wgdashboard/src/dashboard.py", line 1702, in get_host_bind
    init_dashboard()
  File "/home/iliya/wgdashboard/src/dashboard.py", line 1641, in init_dashboard
    config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 30, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 90, in parse
    raise RuntimeError(
RuntimeError: Tried to add broadcast=10.17.255.255 multiple times to eth0, it was already: server ip
| Log files is under log/                                  |
------------------------------------------------------------`

thx for any help

**Comment by Pashtetickus** [comment]
@iilliya 
https://github.com/donaldzou/WGDashboard/issues/191#issuecomment-1510433790
