### ISSUE TITLE
does not start./wgd.sh start

### ISSUE THREAD

**Issue by Asbjorn88** [donaldzou/WGDashboard#192]
I have:
Alpine Linux v3.16
Python 3.10.5
pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)

following the instructions, an error occurs at the startup stage:
```

/wgdashboard/src# ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/wgdashboard/src/gunicorn.conf.py", line 4, in <module>
    app_host, app_port = dashboard.get_host_bind()
  File "/root/wgdashboard/src/dashboard.py", line 1702, in get_host_bind
    init_dashboard()
  File "/root/wgdashboard/src/dashboard.py", line 1641, in init_dashboard
    config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']
  File "/usr/lib/python3.10/site-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
  File "/usr/lib/python3.10/site-packages/ifcfg/parser.py", line 34, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/lib/python3.10/site-packages/ifcfg/parser.py", line 91, in parse
    raise RuntimeError(
RuntimeError: Tried to add prefixlen=128 multiple times to eth0, it was already: 64
| Log files is under log/                                  |
------------------------------------------------------------

```

how to solve the problem?

**Comment by lokidv** [comment]
i have same problem

**Comment by Pashtetickus** [comment]
@evgn88 @lokidv 
https://github.com/donaldzou/WGDashboard/issues/191#issuecomment-1510433790

**Comment by DaanSelen** [comment]
Closing due to inactivity :-) resubmit an issue if you still encounter it.
