### ISSUE TITLE
wgdashboard webui login error log

### ISSUE THREAD

**Issue by gngpp** [donaldzou/WGDashboard#193]
**Describe The Problem**
[2022-08-27 17:05:22,704] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/etc/wireguard/wgdashboard/src/dashboard.py", line 734, in index
    return render_template('index.html', conf=get_conf_list(), msg=msg)
  File "/etc/wireguard/wgdashboard/src/dashboard.py", line 502, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "/etc/wireguard/wgdashboard/src/dashboard.py", line 419, in get_conf_pub_key
    pub = subprocess.check_output(f"echo '{pri}' | wg pubkey", shell=True, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo '+FaebS51JN7fxr77uMFg5WwDLFJZdls7F/ZULN+uOF4=  # 填写本机的privatekey 内容' | wg pubkey' returned non-zero exit status 1.

- wg version
```
wireguard-tools v1.0.20210223 - https://git.zx2c4.com/wireguard-tools/
```

**Comment by prologonline** [comment]
@gngpp
I had these errors too).
You need to install Python 3.7 and pip3. And all be fine.

**Comment by wh-at-ev-er** [comment]
Hi @gngpp 
Do you remember how or if you resolved this? Am facing same issue now. 
Thanks

**Comment by gngpp** [comment]
> Hi @gngpp Do you remember how or if you resolved this? Am facing same issue now. Thanks

It's been so long that I can't remember how to solve the problem

**Comment by wh-at-ev-er** [comment]
Issue is caused by WG not beinginstalled on the server. It is running within a docker container
