### ISSUE TITLE
after upgrade from debian 11 to debian 12

### ISSUE THREAD

**Issue by Psycho85stgt** [donaldzou/WGDashboard#226]
if update from debian 11.7 to debian 12

do a "apt autoremove" for all in the log given not used programms

error:

debian-01:~/**wgdashboard/src# ./wgd.sh start**
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgdashboard/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/wgdashboard/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/root/wgdashboard/src/dashboard.py", line 23, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
| Log files is under log/                                  |
------------------------------------------------------------

**Comment by davtalor** [comment]
Did you fine a resolution to the problem?

**Comment by Psycho85stgt** [comment]
Hi Donald,
I run back to Debian 11.7.

because I not a programmer or expert Unix user.
I hope you find a reason zu Update

Am 15. Juni 2023 20:29:30 schrieb davtalor ***@***.***>:

**Comment by orojlo** [comment]
hi
run 
`sudo apt remove python3-blinker`
and after uninstall python-blinker run :
`pip install -r requirements.txt `
and after install requirements just start server ;).

**Comment by Pichas** [comment]
> Did you fine a resolution to the problem?

Hi, you have to use venv.

You can use my script to install 
https://gitlab.com/xxx.mailg/wg-db

**Comment by davtalor** [comment]
> Hi Donald, I run back to Debian 11.7. because I not a programmer or expert Unix user. I hope you find a reason zu Update Am 15. Juni 2023 20:29:30 schrieb davtalor ***@***.***>:
> […](#)
> Did you fine a resolution to the problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Worked Perfectly!!! Thank you

**Comment by davtalor** [comment]
> hi run `sudo apt remove python3-blinker` and after uninstall python-blinker run : `pip install -r requirements.txt ` and after install requirements just start server ;).

This worked perfectly!!!! Thank you.

**Comment by Kofl** [comment]
Also works for Ubuntu 20 LTS to 22 LTS update with the error:

Traceback (most recent call last):
  File "/root/wireguard-dashboard/src/dashboard.py", line 9, in <module>
    from flask import Flask, request, render_template, redirect, url_for, session, abort, jsonify
ModuleNotFoundError: No module named 'flask'

**Comment by alexunderboots** [comment]
use `pip install flask flask-qrcode --break-system-packages`
it work for me on Debian 12

**Comment by donaldzou** [comment]
Close due to inactivity.
