### ISSUE TITLE
symbol '-' in wg interface name

### ISSUE THREAD

**Issue by BorisKGB** [donaldzou/WGDashboard#250]
**Describe The Problem**
I created wg configuration named 'wg-intranet.conf' and get dashboard crashing with
```
python3[600]: [2024-01-08 16:23:46,776] ERROR in app: Exception on / [GET]
python3[600]: Traceback (most recent call last):
python3[600]:   File "/usr/src/wgdashboard/src/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
python3[600]:     response = self.full_dispatch_request()
python3[600]:   File "/usr/src/wgdashboard/src/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
python3[600]:     rv = self.handle_user_exception(e)
python3[600]:   File "/usr/src/wgdashboard/src/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
python3[600]:     rv = self.dispatch_request()
python3[600]:   File "/usr/src/wgdashboard/src/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
python3[600]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
python3[600]:   File "/usr/src/wgdashboard/src/dashboard.py", line 734, in index
python3[600]:     return render_template('index.html', conf=get_conf_list(), msg=msg)
python3[600]:   File "/usr/src/wgdashboard/src/dashboard.py", line 501, in get_conf_list
python3[600]:     g.cur.execute(create_table)
python3[600]: sqlite3.OperationalError: near "-": syntax error
python3[600]: 192.168.148.252 - - [08/Jan/2024 16:23:46] "GET / HTTP/1.1" 500 -
```

**I use:**
 - Debian 11.8
 - Python 3.9.2
 - `DASHBOARD_VERSION = 'v3.0.6'`

**Comment by BorisKGB** [comment]
I changed `get_conf_list()` method in `dashboard.py`
https://github.com/donaldzou/WGDashboard/blob/main/src/dashboard.py#L491 to `CREATE TABLE IF NOT EXISTS '%s' (`
and
https://github.com/donaldzou/WGDashboard/blob/main/src/dashboard.py#L501 to `g.cur.execute(create_table % i)`

After restarting the service, I get the same error in another sqlite query in the code. Now you just need to apply this change to other sqlite queries.

**Comment by donaldzou** [comment]
This issue is fixed in v4 :)
