### ISSUE TITLE
When running v4 it gives me this error

### ISSUE THREAD

**Issue by jemartinezp1994** [donaldzou/WGDashboard#270]
root@mypc:~/wgd/src# ./wgd.sh start
------------------------------------------------------------
| Starting WGDashboard with Gunicorn in the background.    |
Failed to read config file: /root/wgd/src/gunicorn.conf.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/wgd/src/gunicorn.conf.py", line 2, in <module>
    import dashboard
  File "/root/wgd/src/dashboard.py", line 1244
    return "Public key already exist."
    ^
IndentationError: unexpected indent
| Log files is under log/

**Comment by DaanSelen** [comment]
Can you perhaps give some context to where you installed it, how, etc? I do suggest running the application not as root.

**Comment by donaldzou** [comment]
This is caused by v4 was still in development and the code is incomplete.
