### ISSUE TITLE
Tunnel Creation issue | Dashboard randomly quits

### ISSUE THREAD

**Issue by qvipin** [donaldzou/WGDashboard#493]
**Describe The Problem**
As seen in the video, it seems like the dashboard just breaks and logs me out when I am attempting to create a tunnel.

https://files.vipin.xyz/api/public/dl/-_vRYKhq?inline=true

**To Reproduce**
Default everything; endpoint ip changed in peer settings.

**OS Information:**
Proxmox VM; 1 Core, 2 Gigs of memory

**Comment by donaldzou** [comment]
Hi! can you try to run this in debug mode, as in `./wgd.sh debug` and see what it will output please?

**Comment by qvipin** [comment]
```
ubuntu@wireguard:~/WGDashboard/src$ ./wgd.sh debug
------------------------------------------------------------
[WGDashboard] WireGuard is already installed.
[WGDashboard] Starting WGDashboard in the foreground.
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
 * Serving Flask app 'WGDashboard'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10086
 * Running on http://192.168.4.212:10086
Press CTRL+C to quit
192.168.4.184 - - [15/Nov/2024 22:54:57] "GET / HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:54:57] "GET /api/locale HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:54:57] "GET /api/getDashboardTheme HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:54:57] "GET /api/isTotpEnabled HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:54:57] "GET /api/getDashboardVersion HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "POST /api/authenticate HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /api/validateAuthentication HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /static/app/dist/assets/index-BKNwSldE.css HTTP/1.1" 304 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /static/app/dist/assets/configurationList-DXiA3PJG.js HTTP/1.1" 304 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /static/app/dist/assets/configurationList-CWcGXYWr.css HTTP/1.1" 304 -
192.168.4.184 - - [15/Nov/2024 22:55:21] "GET /static/app/dist/assets/index-Cpk4tyPJ.js HTTP/1.1" 304 -
192.168.4.184 - - [15/Nov/2024 22:55:22] "GET /api/getWireguardConfigurations HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:22] "GET /api/getDashboardUpdate HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:24] "GET /api/validateAuthentication HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:24] "GET /api/getDashboardConfiguration HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:24] "GET /static/app/dist/assets/index-L60y6kc9.js HTTP/1.1" 304 -
192.168.4.184 - - [15/Nov/2024 22:55:24] "GET /static/app/dist/assets/newConfiguration-Cs88Tt1v.js HTTP/1.1" 200 -
[2024-11-15 22:55:37,610] ERROR in app: Exception on /api/addWireguardConfiguration [POST]
Traceback (most recent call last):
  File "/home/ubuntu/WGDashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/dashboard.py", line 1805, in API_addWireguardConfiguration
    WireguardConfigurations[data['ConfigurationName']] = WireguardConfiguration(data=data)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/WGDashboard/src/dashboard.py", line 489, in __init__
    self.__parser["Interface"] = {
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 955, in __setitem__
    self.read_dict({key: value})
  File "/usr/lib/python3.12/configparser.py", line 741, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.12/configparser.py", line 1184, in set
    super().set(section, option, value)
  File "/usr/lib/python3.12/configparser.py", line 872, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 374, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE' at position 23
192.168.4.184 - - [15/Nov/2024 22:55:37] "POST /api/addWireguardConfiguration HTTP/1.1" 500 -
192.168.4.184 - - [15/Nov/2024 22:55:38] "GET /api/isTotpEnabled HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:38] "GET /api/getDashboardTheme HTTP/1.1" 200 -
192.168.4.184 - - [15/Nov/2024 22:55:38] "GET /api/getDashboardVersion HTTP/1.1" 200 -
```

Did the exact same thing as in the video, judging by the errors it says my post up and down is wrong but idk tbh, I will still post them here.

Post Up: iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

Post Down: iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

**Comment by donaldzou** [comment]
Hi! This is an issue we need to fix.. Meanwhile, what you can do is:
1. Turn off WGDashboard
2. Edit this configuration's `.conf` file with a text editor
3. Replace all `%i` with your configuration's name in all Post/Pre Up and Down.
4. Save
5. Restart WGDashboard

Let me know if this works :)

**Comment by donaldzou** [comment]
Closing this due to inactivity.
