### ISSUE TITLE
After updating WGDashboard to version 4.1.0, it is no longer possible to log in.

### ISSUE THREAD

**Issue by eje-1** [donaldzou/WGDashboard#509]
**Describe The Problem**
After updating WGDashboard to version 4.1.0, it is no longer possible to log in. An error is raised when attempting to authenticate.

**Expected Error / Traceback**
```
[2024-11-20 16:13:31,271] ERROR in app: Exception on /api/authenticate [POST]
Traceback (most recent call last):
  File "/opt/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wgdashboard/src/venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/opt/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wgdashboard/src/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wgdashboard/src/dashboard.py", line 1727, in API_AuthenticateLogin
    valid = bcrypt.checkpw(data['password'].encode("utf-8"),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid salt

```

**To Reproduce**
1. Update WGDashboard to version 4.0.1.
2. Start the application: ./wgd.sh start.
3. Try to log in with the default credentials (e.g., username: admin, password: admin).
4. The above traceback is generated, and login is unsuccessful.

**OS Information:**
 - OS: [e.g. Ubuntu 20.04LTS]
 - Python3 Version: [e.g  3.12.3 ]
 
In this version v3.0.6 everything was good.
Many thanks in advance!

**Comment by DaanSelen** [comment]
Did you come from any version before 4.0.x? If yes, remove the  `password` field from the wg-dashboard.ini?
