### ISSUE TITLE
After first configuration, restart not working anymore

### ISSUE THREAD

**Issue by Bastika07** [donaldzou/WGDashboard#542]
./wgd.sh start
[WGDashboard] WireGuard is already installed.
------------------------------------------------------------
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
Failed to read config file: ./gunicorn.conf.py
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 110, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/WGDashboard/src/./gunicorn.conf.py", line 1, in <module>
    import dashboard
  File "/root/WGDashboard/src/dashboard.py", line 1649, in <module>
    DashboardConfig = DashboardConfig()
                      ^^^^^^^^^^^^^^^^^
  File "/root/WGDashboard/src/dashboard.py", line 1348, in __init__
    "remote_endpoint": ifcfg.default_interface()['inet'] if ifcfg.default_interface() else '',
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/WGDashboard/src/venv/lib/python3.11/site-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/WGDashboard/src/venv/lib/python3.11/site-packages/ifcfg/parser.py", line 34, in __init__
    self.parse(self.ifconfig_data)
  File "/root/WGDashboard/src/venv/lib/python3.11/site-packages/ifcfg/parser.py", line 76, in parse
    raise RuntimeError(
RuntimeError: Got results that don't belong to a device

python3.11
debian 12.07

**Comment by donaldzou** [comment]
Hi, could you let me know what does `ifconfig` returns for you? If anything seems normal, try the following:

(assuming you're in `wgdashboard/src`)

```
./venv/bin/python3 -m pip install -r requirements.txt
```
