### ISSUE TITLE
Random crashes of the ui / random log outs

### ISSUE THREAD

**Issue by reloadlife** [donaldzou/WGDashboard#559]
it seems like `getWireguardConfiguration` endpoints (most of the time it's this one) 
or other endpoints, can result in a "500 Internal server Error" and instead of treating it as an Error, the ui seems to treat it as a 401 and results in redirecting the user back to the login page, and it's annoying and keeps the user form using the panel.

**Comment by donaldzou** [comment]
Hi, could you please post the l`access_2024.....log` with the latest date? So we can look into which endpoint is causing and why.

**Comment by MazBazDev** [comment]
@donaldzou  I encounter the same issue :) 

root@guard:~/WGDashboard/src# cat ./log/error_2024_12_30_18_45_21.log
[2024-12-30 18:45:21 +0000] [1141] [INFO] Starting gunicorn 23.0.0
[2024-12-30 18:45:21 +0000] [1141] [INFO] Listening at: http://0.0.0.0:10086 (1141)
[2024-12-30 18:45:21 +0000] [1141] [INFO] Using worker: gthread
[2024-12-30 18:45:21 +0000] [1143] [INFO] Booting worker with pid: 1143
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
[2024-12-30 18:52:18,253] ERROR in app: Exception on /api/traceroute/execute [GET]
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 108, in resolve
    lookup = socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WGDashboard/src/dashboard.py", line 2391, in API_traceroute_execute
    tracerouteResult = traceroute(ipAddress, timeout=1, max_hops=64)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/traceroute.py", line 158, in traceroute
    address = resolve(address, family)[0]
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 118, in resolve
    return resolve(name, 6)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 120, in resolve
    raise NameLookupError(name)
icmplib.exceptions.NameLookupError: The name 'google.com' cannot be resolved

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/WGDashboard/src/dashboard.py", line 2427, in API_traceroute_execute
    return ResponseObject(False, exp)
  File "/root/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/WGDashboard/src/dashboard.py", line 75, in default
    return super().default(self, o)
TypeError: _default() takes 1 positional argument but 2 were given
[2024-12-30 18:52:36,846] ERROR in app: Exception on /api/traceroute/execute [GET]
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 108, in resolve
    lookup = socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WGDashboard/src/dashboard.py", line 2391, in API_traceroute_execute
    tracerouteResult = traceroute(ipAddress, timeout=1, max_hops=64)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/traceroute.py", line 158, in traceroute
    address = resolve(address, family)[0]
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 118, in resolve
    return resolve(name, 6)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/icmplib/utils.py", line 120, in resolve
    raise NameLookupError(name)
icmplib.exceptions.NameLookupError: The name 'google.com' cannot be resolved

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/WGDashboard/src/dashboard.py", line 2427, in API_traceroute_execute
    return ResponseObject(False, exp)
  File "/root/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/root/WGDashboard/src/dashboard.py", line 75, in default
    return super().default(self, o)
TypeError: _default() takes 1 positional argument but 2 were given
[2024-12-30 20:37:36,126] ERROR in app: Exception on /api/addWireguardConfiguration [POST]
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/WGDashboard/src/dashboard.py", line 1814, in API_addWireguardConfiguration
    WireguardConfigurations[data['ConfigurationName']] = WireguardConfiguration(data=data)
  File "/root/WGDashboard/src/dashboard.py", line 463, in __init__
    self.__configPath = os.path.join(DashboardConfig.GetConfig("Server", "wg_conf_path")[1], f'{self.Name}.conf')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-12-30 20:38:04,712] ERROR in app: Exception on /api/addWireguardConfiguration [POST]
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/WGDashboard/src/dashboard.py", line 1814, in API_addWireguardConfiguration
    WireguardConfigurations[data['ConfigurationName']] = WireguardConfiguration(data=data)
  File "/root/WGDashboard/src/dashboard.py", line 463, in __init__
    self.__configPath = os.path.join(DashboardConfig.GetConfig("Server", "wg_conf_path")[1], f'{self.Name}.conf')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-12-30 20:40:50,633] ERROR in app: Exception on /api/getAllWireguardConfigurationBackup [GET]
Traceback (most recent call last):
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/WGDashboard/src/dashboard.py", line 1889, in API_getAllWireguardConfigurationBackup
    for file in os.listdir(directory) if os.path.isfile(os.path.join(directory, file))]
FileNotFoundError: [Errno 2] No such file or directory: '/etc/wireguard/WGDashboard_Backup'

**Comment by MazBazDev** [comment]
I did a fresh install of wg dashboard, followed every step of the documentation.
If I want to create a new configuration, every time I try to save I get disconnected, to fix this I had to change the IP Address/Hostname setting and restart the dashboard and finally everything worked fine :)

**Comment by donaldzou** [comment]
This is so weird never seen this issue before.. do you mind telling me what exactly did you do to fix it?

**Comment by reloadlife** [comment]
i totally forgot to post this here:

```text
[2024-12-30 17:57:58,504] ERROR in app: Exception on /api/getWireguardConfigurationInfo [GET]
Traceback (most recent call last):
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/WGDashboard/src/dashboard.py", line 2255, in API_getConfigurationInfo
    "configurationPeers": WireguardConfigurations[configurationName].getPeersList(),
  File "/opt/WGDashboard/src/dashboard.py", line 990, in getPeersList
    self.__getPeers()
  File "/opt/WGDashboard/src/dashboard.py", line 720, in __getPeers
    self.Peers.append(Peer(i, self))
  File "/opt/WGDashboard/src/dashboard.py", line 1180, in __init__
    self.getShareLink()
  File "/opt/WGDashboard/src/dashboard.py", line 1286, in getShareLink
    self.ShareLink = AllPeerShareLinks.getLink(self.configuration.Name, self.id)
  File "/opt/WGDashboard/src/dashboard.py", line 410, in getLink
    self.__getSharedLinks()
  File "/opt/WGDashboard/src/dashboard.py", line 405, in __getSharedLinks
    allLinks = sqlSelect("SELECT * FROM PeerShareLinks WHERE ExpireDate IS NULL OR ExpireDate > datetime('now', 'localtime')").fetchall()
  File "/opt/WGDashboard/src/dashboard.py", line 1628, in sqlSelect
    with sqldb:
sqlite3.OperationalError: cannot commit - no transaction is active
```

**Comment by donaldzou** [comment]
@reloadlife The latest version should fix it. Could you try to update it by doing `./wgd.sh update` and see if the issue still persist?

**Comment by reloadlife** [comment]
@donaldzou seems like no
it still happens and i get redirected back to Signin page:

here's the log:

```
[2025-01-02 05:45:47,590] ERROR in app: Exception on /api/getWireguardConfigurationInfo [GET]
Traceback (most recent call last):
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/WGDashboard/src/dashboard.py", line 2253, in API_getConfigurationInfo
    return ResponseObject(data={
  File "/opt/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/app.py", line 1193, in make_response
    rv = self.json.response(rv)
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/opt/WGDashboard/src/venv/lib/python3.10/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/WGDashboard/src/dashboard.py", line 74, in default
    return o.toJson()
  File "/opt/WGDashboard/src/dashboard.py", line 1184, in toJson
    self.getShareLink()
  File "/opt/WGDashboard/src/dashboard.py", line 1286, in getShareLink
    self.ShareLink = AllPeerShareLinks.getLink(self.configuration.Name, self.id)
  File "/opt/WGDashboard/src/dashboard.py", line 410, in getLink
    self.__getSharedLinks()
  File "/opt/WGDashboard/src/dashboard.py", line 405, in __getSharedLinks
    allLinks = sqlSelect("SELECT * FROM PeerShareLinks WHERE ExpireDate IS NULL OR ExpireDate > datetime('now', 'localtime')").fetchall()
  File "/opt/WGDashboard/src/dashboard.py", line 1628, in sqlSelect
    with sqldb:
sqlite3.DatabaseError: no more rows available
```

**Comment by donaldzou** [comment]
@reloadlife Hi I think you didn't successfully update the dashboard, since I removed the `with sqldb` in the code... maybe you can try `git pull` in the directory?

**Comment by donaldzou** [comment]
Wasn't able to recreate this issue.. Will close this issue for now.
