### ISSUE TITLE
WGDashboard constantly throws you to the authorization page

### ISSUE THREAD

**Issue by ozels** [donaldzou/WGDashboard#562]
**Describe The Problem**
Hello, after a while, the WGDashboard constantly throws you to the authorization page. If you click "back (arrow)" on the authorization page in the browser, it continues to work, but after a while it throws you back to the authorization page.
How to fix this? Please help.

**Expected Error / Traceback**
```
[2024-12-26 15:47:10 +0300] [77210] [INFO] Starting gunicorn 23.0.0
[2024-12-26 15:47:10 +0300] [77210] [INFO] Listening at: http://192.168.220.160:10086 (77210)
[2024-12-26 15:47:10 +0300] [77210] [INFO] Using worker: gthread
[2024-12-26 15:47:10 +0300] [77212] [INFO] Booting worker with pid: 77212
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
[2024-12-26 15:48:15,198] ERROR in app: Exception on /api/getWireguardConfigurationInfo [GET]
Traceback (most recent call last):
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 2253, in API_getConfigurationInfo
    return ResponseObject(data={
           ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 74, in default
    return o.toJson()
           ^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1184, in toJson
    self.getShareLink()
  File "/srv/WGDashboard/src/dashboard.py", line 1286, in getShareLink
    self.ShareLink = AllPeerShareLinks.getLink(self.configuration.Name, self.id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 410, in getLink
    self.__getSharedLinks()
  File "/srv/WGDashboard/src/dashboard.py", line 405, in __getSharedLinks
    allLinks = sqlSelect("SELECT * FROM PeerShareLinks WHERE ExpireDate IS NULL OR ExpireDate > datetime('now', 'localtime')").fetchall()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1628, in sqlSelect
    with sqldb:
SystemError: error return without exception set
```

Raspberry Pi 3
**OS Information:**
 - OS: Raspbian12 PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
 - Python Version: Python 3.12.5

**Sample of your `.conf` file**
```
[Interface]
Address = 33.33.33.1/24
DNS = 127.0.0.1
PostUp = iptables -I INPUT -p udp --dport 34728 -j ACCEPT
PostUp = iptables -I FORWARD -i eth0 -o wg0 -j ACCEPT
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip rule add from `ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | grep -v "inet6" | head -n 1 | awk '/inet/ {print $2}' | awk -F/ '{print $1}'` table main
PostDown = iptables -D INPUT -p udp --dport 34728 -j ACCEPT
PostDown = iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip rule del from `ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | grep -v "inet6" | head -n 1 | awk '/inet/ {print $2}' | awk -F/ '{print $1}'` table main
ListenPort = 34728
FwMark = 0xca6c
PrivateKey = ABCD...

[Peer]
PublicKey = EuKyomV9f2nK/FPXt+5OUla3IKON6Nn/3WtYPv1zcVo=
AllowedIPs = 33.33.33.111/32, 0.0.0.0/0
Endpoint = x.x.x.x:53628

[Peer]
PublicKey = M+bGYfx6NNhRnTyJgLZ1NTaS5Mzr1hE4b07cy1exxF0=
AllowedIPs = 33.33.33.2/32, 192.168.5.0/24
Endpoint = x.x.x.x:44582
```

**Comment by DaanSelen** [comment]
@ozels if you are able can you try again with the latest code once that's merged?

**Comment by donaldzou** [comment]
@ozels The new update should fix the issue :) You can update it by doing `./wgd.sh update`

**Comment by ozels** [comment]
Hello, sorry for taking a long time to respond, I was sick. Unfortunately, the problem has not been solved. settings too. Here is the new log.
````
root@gatewey-vpn:/srv/WGDashboard/src# cat ./log/error_2024_12_30_14_20_14.log
[2024-12-30 14:20:14 +0300] [87221] [INFO] Starting gunicorn 23.0.0
[2024-12-30 14:20:14 +0300] [87221] [INFO] Listening at: http://192.168.220.160:10086 (87221)
[2024-12-30 14:20:14 +0300] [87221] [INFO] Using worker: gthread
[2024-12-30 14:20:14 +0300] [87223] [INFO] Booting worker with pid: 87223
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
[2024-12-30 14:24:13,488] ERROR in app: Exception on /api/getWireguardConfigurationInfo [GET]
Traceback (most recent call last):
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 2253, in API_getConfigurationInfo
    return ResponseObject(data={
           ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 74, in default
    return o.toJson()
           ^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1184, in toJson
    self.getShareLink()
  File "/srv/WGDashboard/src/dashboard.py", line 1286, in getShareLink
    self.ShareLink = AllPeerShareLinks.getLink(self.configuration.Name, self.id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 410, in getLink
    self.__getSharedLinks()
  File "/srv/WGDashboard/src/dashboard.py", line 405, in __getSharedLinks
    allLinks = sqlSelect("SELECT * FROM PeerShareLinks WHERE ExpireDate IS NULL OR ExpireDate > datetime('now', 'localtime')").fetchall()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1628, in sqlSelect
    with sqldb:
sqlite3.OperationalError: cannot commit - no transaction is active

````

**Comment by DaanSelen** [comment]
Perhaps the timezone?

**Comment by ozels** [comment]
> Может быть, часовой пояс?

The time on the server is correct.

**Comment by ozels** [comment]
> Perhaps the timezone?

**Comment by donaldzou** [comment]
Let me merge a changes to main and hope this works :(

**Comment by donaldzou** [comment]
@ozels Could you please update and try again?

**Comment by ozels** [comment]
After the update the problem remained. New log after the update.
````
[2025-01-04 14:10:33 +0300] [198832] [INFO] Starting gunicorn 23.0.0
[2025-01-04 14:10:33 +0300] [198832] [INFO] Listening at: http://192.168.220.160:10086 (198832)
[2025-01-04 14:10:33 +0300] [198832] [INFO] Using worker: gthread
[2025-01-04 14:10:33 +0300] [198834] [INFO] Booting worker with pid: 198834
[WGDashboard] Background Thread #1 Started
[WGDashboard] Background Thread #2 Started
[2025-01-04 14:15:06,880] ERROR in app: Exception on /api/getWireguardConfigurationInfo [GET]
Traceback (most recent call last):
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 2253, in API_getConfigurationInfo
    return ResponseObject(data={
           ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 54, in ResponseObject
    response = Flask.make_response(app, {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/app.py", line 1231, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/venv/lib/python3.11/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 74, in default
    return o.toJson()
           ^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1184, in toJson
    self.getShareLink()
  File "/srv/WGDashboard/src/dashboard.py", line 1286, in getShareLink
    self.ShareLink = AllPeerShareLinks.getLink(self.configuration.Name, self.id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 410, in getLink
    self.__getSharedLinks()
  File "/srv/WGDashboard/src/dashboard.py", line 405, in __getSharedLinks
    allLinks = sqlSelect("SELECT * FROM PeerShareLinks WHERE ExpireDate IS NULL OR ExpireDate > datetime('now', 'localtime')").fetchall()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/WGDashboard/src/dashboard.py", line 1628, in sqlSelect
    with sqldb:
sqlite3.OperationalError: cannot commit - no transaction is active
````

**Comment by donaldzou** [comment]
Hi, can you please update with `git pull` in the directory? I don't think you update it successfully

**Comment by ozels** [comment]
> Hi, can you please update with `git pull` in the directory? I don't think you update it successfully

Yes, you were right. I updated the repository branch and did more just in case `./wgd.sh update`, during the hour of the panel's operation, there was not a single departure. Thank you so much for your help and for your hard work. Good luck with everything.
👍
