### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dpins0n** [donaldzou/WGDashboard#58]
Something happened when I tried to add a peer. I was using the previous version, and everything seemed to be OK. 
It looked like the app was trying to parse a sample conf file I had created to be able to quickly make client config files.
I renamed that sample file to xyz instead of sample.conf, but still had the internal server error.
I saw that there was a new version, so I upgraded to v2.2.1.
Now I am getting an "IndexError: list index out of range" when trying to expand wg0.
The browser app never finishes, it loops on the error.

**Expected Error / Traceback**
```
[2021-08-17 12:23:28,128] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 715, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 248, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 239, in get_all_peers_data
    get_transfer(config_name, db, peers)
  File "dashboard.py", line 159, in get_transfer
    total_sent = cur_i[0]['total_sent']
IndexError: list index out of range
96.241.154.2 - - [17/Aug/2021 12:23:28] "GET /get_config/wg0?search= HTTP/1.1" 500 -
96.241.154.2 - - [17/Aug/2021 12:23:35] "GET /get_config/wg0 HTTP/1.1" 302 -
96.241.154.2 - - [17/Aug/2021 12:23:36] "GET /signin HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:36] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:36] "GET /static/logo.png HTTP/1.1" 404 -
96.241.154.2 - - [17/Aug/2021 12:23:36] "GET /static/js/bootstrap.bundle.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:37] "GET /static/js/tools.js HTTP/1.1" 200 -
[2021-08-17 12:23:43,054] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 715, in get_conf
    "peer_data": get_peers(config_name, search, sort),
  File "dashboard.py", line 248, in get_peers
    get_all_peers_data(config_name)
  File "dashboard.py", line 239, in get_all_peers_data
    get_transfer(config_name, db, peers)
  File "dashboard.py", line 159, in get_transfer
    total_sent = cur_i[0]['total_sent']
IndexError: list index out of range
96.241.154.2 - - [17/Aug/2021 12:23:43] "GET /get_config/wg0?search= HTTP/1.1" 500 -
96.241.154.2 - - [17/Aug/2021 12:23:50] "GET /get_config/wg0 HTTP/1.1" 302 -
96.241.154.2 - - [17/Aug/2021 12:23:51] "GET /signin HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:51] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:51] "GET /static/logo.png HTTP/1.1" 404 -
96.241.154.2 - - [17/Aug/2021 12:23:51] "GET /static/js/bootstrap.bundle.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 12:23:52] "GET /static/js/tools.js HTTP/1.1" 200 -
```

**To Reproduce**
```
./wgd.sh start

wg-dashboard.ini
[Account]
username = admin
password = *****

[Server]
wg_conf_path = /etc/wireguard
app_ip = 0.0.0.0
app_port = 8080
auth_req = true
version = v2.2.1
dashboard_refresh_interval = 15000
dashboard_sort = status

[Peers]
peer_global_dns = 1.1.1.1
peer_endpoint_allowed_ip = 0.0.0.0/0

**OS Information:**
Ubuntu 20.04.2 LTS
Python 3.8
```

**Sample of your `.conf` file**
```
[Interface]
Address = 192.168.17.1/24
ListenPort = 51820
PrivateKey = *****

[Peer]
PublicKey = *****
AllowedIPs = 192.168.17.200/32
Endpoint = 73.172.125.95:52252

[Peer]
PublicKey = ****
AllowedIPs = 192.168.17.41/32
Endpoint = 96.241.154.2:50220

[Peer]
PublicKey = *****
AllowedIPs = 192.168.17.199/32
Endpoint = 96.241.154.2:39351

[Peer]
PublicKey = *****
AllowedIPs = 192.168.17.55/32
Endpoint = 96.241.154.2:55499

[Peer]
PublicKey = *****
AllowedIPs = 192.168.17.183/32

```

**Comment by donaldzou** [comment]
Hi, it seems like there are extra peers returned by `wg show wg0 transfer`. Do you mind to stop the dashboard, copy all the `.json` files under `wireguard-dashboard/src/db` to somewhere, and then restart the dashboard to see if it solve the bug.

**Comment by dpins0n** [comment]
It looks about the same...

2021-08-17 16:07:01,633] ERROR in app: Exception on /get_config/wg0
[GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070,
in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515,
in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513,
in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499,
in dispatch_request
return
self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "dashboard.py", line 715, in get_conf
"peer_data": get_peers(config_name, search, sort),
File "dashboard.py", line 248, in get_peers
get_all_peers_data(config_name)
File "dashboard.py", line 239, in get_all_peers_data
get_transfer(config_name, db, peers)
File "dashboard.py", line 159, in get_transfer
total_sent = cur_i[0]['total_sent']
IndexError: list index out of range
96.241.154.2 - - [17/Aug/2021 16:07:01] "GET /get_config/wg0?search=
HTTP/1.1" 500 -
96.241.154.2 - - [17/Aug/2021 16:07:06] "GET /get_config/wg0 HTTP/1.1"
302 -
96.241.154.2 - - [17/Aug/2021 16:07:06] "GET /signin HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:07] "GET /static/js/jquery.min.js
HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:07] "GET /static/logo.png HTTP/1.1"
404 -
96.241.154.2 - - [17/Aug/2021 16:07:07] "GET
/static/js/bootstrap.bundle.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:08] "GET /static/js/tools.js
HTTP/1.1" 200 -
[2021-08-17 16:07:16,643] ERROR in app: Exception on /get_config/wg0
[GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070,
in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515,
in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513,
in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499,
in dispatch_request
return
self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "dashboard.py", line 715, in get_conf
"peer_data": get_peers(config_name, search, sort),
File "dashboard.py", line 248, in get_peers
get_all_peers_data(config_name)
File "dashboard.py", line 239, in get_all_peers_data
get_transfer(config_name, db, peers)
File "dashboard.py", line 159, in get_transfer
total_sent = cur_i[0]['total_sent']
IndexError: list index out of range
96.241.154.2 - - [17/Aug/2021 16:07:16] "GET /get_config/wg0?search=
HTTP/1.1" 500 -
96.241.154.2 - - [17/Aug/2021 16:07:21] "GET /get_config/wg0 HTTP/1.1"
302 -
96.241.154.2 - - [17/Aug/2021 16:07:21] "GET /signin HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:22] "GET /static/js/jquery.min.js
HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:22] "GET /static/logo.png HTTP/1.1"
404 -
96.241.154.2 - - [17/Aug/2021 16:07:22] "GET
/static/js/bootstrap.bundle.js HTTP/1.1" 200 -
96.241.154.2 - - [17/Aug/2021 16:07:23] "GET /static/js/tools.js
HTTP/1.1" 200 -

**Comment by donaldzou** [comment]
Can you try `wg-quick down wg0` and then remove all the `.json` files under `db`? And then restart the dashboard without turning on the interface. Sorry about the complication.

**Comment by dpins0n** [comment]
That allows me to see the peers. If I use the switch to start wg0, I get the index error.

**Comment by donaldzou** [comment]
This is so weird, I need to look into this problem and I will get back to you as fast as I can.

**Comment by donaldzou** [comment]
could you provide the copy of the result when you execute `wg show wg0` and `wg show wg0 transfer`? You replace all you keys with something else. Thank you very much!

**Comment by patrick-mota** [comment]
I had the exact same error.
Didn't saw but my tunnel wasn't working completly.

I could ping from VPS to VPS
I couldn't ping from VPS to CLIENT

I could ping from CLIENT to CLIENT
I couldn't ping from CLIENT to VPS

I fixed the problem, restarted the wg0 in the VPS (server) and it solved the issue.

So I think the interface will not load if wireguard can't return information about peers, maybe putting a try/catch with this kind of unexpected errors and a friend message for the disconnected peer.

**Comment by donaldzou** [comment]
I think this will get solved in the next release ;)
