### ISSUE TITLE
RuntimeError: Tried to add netmask=/32 multiple times to lo, it was already: /8

### ISSUE THREAD

**Issue by RatakondalaArun** [donaldzou/WGDashboard#82]
**Describe The Problem**
Throws a exception

**Expected Error / Traceback**
```bash
Traceback (most recent call last):
  File "dashboard.py", line 1166, in <module>
    init_dashboard()
  File "dashboard.py", line 1140, in init_dashboard
    config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 30, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.8/dist-packages/ifcfg/parser.py", line 90, in parse
    raise RuntimeError(
RuntimeError: Tried to add netmask=/32 multiple times to lo, it was already: /8
```

**To Reproduce**
Run the script

**OS Information:**
 - OS: `Ubuntu 20.04`
 - Python Version: `v3.8.10`

**Sample of your `.conf` file**
```conf
[Interface]
Address = 10.0.0.1/16
ListenPort = 51820
PrivateKey = ****
SaveConfig = false


[Peer]
# admin
PublicKey = ****
PresharedKey = ****
AllowedIPs = 10.0.0.2/32
```
note: I use [Alog] (https://github.com/trailofbits/algo) to configure Wireguard.

**Comment by donaldzou** [comment]
Hi, does your "Server" have a default IP from `ifconfig`?

**Comment by RatakondalaArun** [comment]
Hi @donaldzou, It started working after installing `net-tools` on my server😅.

**Comment by donaldzou** [comment]
Ahhh that makes sense now. I'm glad is working for u :)

**Comment by donaldzou** [comment]
> Hi @donaldzou, It started working after installing `net-tools` on my server😅.

Ahhh that makes sense now. I'm glad is working for u :)
