### ISSUE TITLE
Installation Log fails because of existing docker installation

### ISSUE THREAD

**Issue by nicedevil007** [donaldzou/WGDashboard#84]
**Describe The Problem**
I get an error message because of my already running docker instance during the installation.

**Expected Error / Traceback**
```
root@DietPi:~/wgdashboard/src# cat log/20210916211224.txt
Traceback (most recent call last):
  File "dashboard.py", line 1166, in <module>
    init_dashboard()
  File "dashboard.py", line 1140, in init_dashboard
    config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']
  File "/usr/local/lib/python3.7/dist-packages/ifcfg/__init__.py", line 81, in default_interface
    return Parser(ifconfig=ifconfig)._default_interface(route_output=route_output)
  File "/usr/local/lib/python3.7/dist-packages/ifcfg/parser.py", line 30, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.7/dist-packages/ifcfg/parser.py", line 95, in parse
    self._interfaces[cur][k]
RuntimeError: Tried to add broadcast=172.18.255.255 multiple times to docker0, it was already: 172.17.255.255
```

**To Reproduce**
Installl wg-dashboard as described on gitub with all prerequisits and then take a look into the logfiles.

**OS Information:**
 - OS: dietpi 7.52
 - Python Version: v3.7

**Sample of your `.conf` file**
```
wasn't able to create one because installation already fails for the dashboard.
```

**Comment by pike00** [comment]
I had a little bit of a look into this as I've had the same problem, and I believe it is a docker networking related issue (specifically there are multiple redundant network interfaces that were created by docker that are no longer in use).

I pruned up the old ones with this command (it ignores any active networks that has active connections, leaving any running networks up): `docker network prune` ([Documentation](https://docs.docker.com/engine/reference/commandline/network_prune)). I was able to get the command to run properly after this and generate the `/src/wg-dashboard.ini`, with the relevant line being this: `remote_endpoint = 192.168.1.2`

I think you can try a brief workaround by changing [line 1140](https://github.com/donaldzou/WGDashboard/blob/922a494df0e2929ecaab825459c7a3d4bb714dbc/src/dashboard.py#L1140) *from* this:
`config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']`

*to* this:
`config['Peers']['remote_endpoint'] = <Your Private LAN IP>`

**Comment by donaldzou** [comment]
Hi, thank you so much for looking into this. Since i'm not a docker expert, I will leave this issue open if anyone have a better solution ;) Cheers!

> I had a little bit of a look into this as I've had the same problem, and I believe it is a docker networking related issue (specifically there are multiple redundant network interfaces that were created by docker that are no longer in use).
> 
> I pruned up the old ones with this command (it ignores any active networks that has active connections, leaving any running networks up): `docker network prune` ([Documentation](https://docs.docker.com/engine/reference/commandline/network_prune)). I was able to get the command to run properly after this and generate the `/src/wg-dashboard.ini`, with the relevant line being this: `remote_endpoint = 192.168.1.2`
> 
> I think you can try a brief workaround by changing [line 1140](https://github.com/donaldzou/WGDashboard/blob/922a494df0e2929ecaab825459c7a3d4bb714dbc/src/dashboard.py#L1140) _from_ this: `config['Peers']['remote_endpoint'] = ifcfg.default_interface()['inet']`
> 
> _to_ this: `config['Peers']['remote_endpoint'] = <Your Private LAN IP>`

**Comment by donaldzou** [comment]
Closing this due to inactivity. Please refer to #272
