### ISSUE TITLE
Installation of Flask-QRcode fails?

### ISSUE THREAD

**Issue by nicedevil007** [donaldzou/WGDashboard#98]
**Describe The Problem**
Title says all.

**Expected Error / Traceback**
```
 ~/wgdashboard/src  #v2.3.1 *1 ?1  pip3 install -r requirements.txt                         ✔  4s  root@wireguard
Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (2.0.2)
Collecting tinydb
  Using cached tinydb-4.5.2-py3-none-any.whl (23 kB)
Requirement already satisfied: ifcfg in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (0.22)
Collecting icmplib
  Using cached icmplib-3.0.1-py3-none-any.whl (30 kB)
Collecting flask-qrcode
  Using cached Flask-QRcode-3.0.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9j4ie7gk/flask-qrcode_de0ac85ef0504b27985c9bf07bb23b33/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9j4ie7gk/flask-qrcode_de0ac85ef0504b27985c9bf07bb23b33/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i72xdism
       cwd: /tmp/pip-install-9j4ie7gk/flask-qrcode_de0ac85ef0504b27985c9bf07bb23b33/
  Complete output (3 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'setuptools'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e0/1d/92745e9f7a0cd02f9ba5de143b8ac3932a88129b2b110812ccc085217840/Flask-QRcode-3.0.0.tar.gz#sha256=96a49da1396a600e79cc4b119610a2e61cb1433f9449994eabf36bbe1478b96b (from https://pypi.org/simple/flask-qrcode/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached Flask-QRcode-2.0.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9j4ie7gk/flask-qrcode_5dd7cb3c99eb4fc0abb5980135d8bbe8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9j4ie7gk/flask-qrcode_5dd7cb3c99eb4fc0abb5980135d8bbe8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qbyvu8u7
       cwd: /tmp/pip-install-9j4ie7gk/flask-qrcode_5dd7cb3c99eb4fc0abb5980135d8bbe8/
  Complete output (3 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'setuptools'
```

**OS Information:**
Linux wireguard 5.11.22-5-pve #1 SMP PVE 5.11.22-10 (Tue, 28 Sep 2021 08:15:41 +0200) x86_64 GNU/Linux

**Comment by nicedevil007** [comment]
This issue seems to be a problem in debian (turnkey-core lxc).
It is not showing up on installing the requirements with an ubuntu lxc

**Comment by donaldzou** [comment]
Hi, I will look into this. Sorry for this super late reply.
